#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────
//  Andromeda — market-monitor seller
//
//  Sells one service: `github-advisory-monitor`
//    • subscribers pay 1000 sat (default) deposit
//    • each delivered alert charges 50 sat
//    • subscriber config: { watched_repos: [...], severity_min: ... }
//
//  Mock mode (default): reads src/fixtures/advisories.json once at
//  boot, fires each on a fast 5s tick.
//  Real mode: polls https://api.github.com/advisories every 60s.
//
//  Note: written in JS rather than TS to keep this a single-file
//  runtime entrypoint. Type definitions for the wire format live in
//  @andromeda/core/types.
// ─────────────────────────────────────────────────────────────────────

import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHmac, randomUUID } from "node:crypto";
import Database from "better-sqlite3";
import { generateKeypair, pubkeyFor, signRequest } from "@andromeda/core";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..", "..");

// ─── env ─────────────────────────────────────────────────────────────
function loadDotEnv() {
  const fp = path.resolve(HERE, "..", ".env");
  if (!fs.existsSync(fp)) return;
  for (const line of fs.readFileSync(fp, "utf8").split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}
loadDotEnv();

const PORT = parseInt(process.env.PORT ?? "3100", 10);
const REGISTRY_URL = process.env.ANDROMEDA_REGISTRY_URL ?? "http://localhost:3030";
const MOCK_MODE = process.env.MOCK_MODE !== "false"; // default true
const PUBLIC_URL = process.env.ANDROMEDA_PROVIDER_PUBLIC_URL ?? `http://localhost:${PORT}`;
const L402_SECRET = process.env.L402_SECRET ?? "";
if (L402_SECRET.length < 32) {
  console.warn("[market-monitor] L402_SECRET <32 chars; alert signatures will be weak");
}
const WATCHER_INTERVAL = parseInt(
  process.env.WATCHER_INTERVAL_MS ?? (MOCK_MODE ? "5000" : "60000"),
  10,
);
const DB_PATH = process.env.ANDROMEDA_MONITOR_DB_PATH ?? path.resolve(HERE, "..", "monitor.db");

// ─── identity ────────────────────────────────────────────────────────
let identity = null;
async function ensureIdentity() {
  if (identity) return identity;
  let priv = process.env.ANDROMEDA_PROVIDER_PRIVKEY;
  if (!priv) {
    const kp = await generateKeypair();
    priv = kp.privkey_hex;
    const fp = path.resolve(HERE, "..", ".env");
    const line = `\n# auto-generated by market-monitor on first boot\nANDROMEDA_PROVIDER_PRIVKEY=${priv}\n`;
    try {
      if (fs.existsSync(fp)) fs.appendFileSync(fp, line, "utf8");
      else fs.writeFileSync(fp, line, "utf8");
      console.error(`[market-monitor] generated keypair; pubkey=${kp.pubkey_hex}`);
    } catch (e) {
      console.error(`[market-monitor] WARN could not persist key: ${e.message}`);
    }
    process.env.ANDROMEDA_PROVIDER_PRIVKEY = priv;
    identity = { privkey: priv, pubkey: kp.pubkey_hex };
    return identity;
  }
  const pubkey = await pubkeyFor(priv);
  identity = { privkey: priv, pubkey };
  return identity;
}

// ─── db ──────────────────────────────────────────────────────────────
const db = new Database(DB_PATH);
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");
db.exec(`
  CREATE TABLE IF NOT EXISTS subscriptions (
    id TEXT PRIMARY KEY,
    subscriber_pubkey TEXT NOT NULL,
    service_local_id TEXT NOT NULL,
    per_event_sats INTEGER NOT NULL,
    balance_sats INTEGER NOT NULL,
    config_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','cancelled','exhausted')),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );
  CREATE TABLE IF NOT EXISTS subscription_alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subscription_id TEXT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    signature TEXT NOT NULL,
    sats_charged INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_alerts_sub ON subscription_alerts(subscription_id, created_at);
  CREATE TABLE IF NOT EXISTS seen_advisories (
    ghsa_id TEXT PRIMARY KEY, seen_at INTEGER NOT NULL
  );
`);

// ─── subscription helpers (same shape as provider/src/lib/db.ts) ─────
const sql = {
  create: db.prepare(`INSERT INTO subscriptions (id, subscriber_pubkey, service_local_id, per_event_sats, balance_sats, config_json, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'active', ?, ?)`),
  get: db.prepare(`SELECT * FROM subscriptions WHERE id = ?`),
  listActive: db.prepare(`SELECT * FROM subscriptions WHERE service_local_id = ? AND status = 'active'`),
  listForSubscriber: db.prepare(`SELECT * FROM subscriptions WHERE subscriber_pubkey = ? ORDER BY created_at DESC`),
  cancel: db.prepare(`UPDATE subscriptions SET status='cancelled', balance_sats=0, updated_at=? WHERE id=? AND status='active'`),
  topup: db.prepare(`UPDATE subscriptions SET balance_sats = balance_sats + ?, updated_at=?, status = CASE WHEN status='exhausted' THEN 'active' ELSE status END WHERE id=? AND status != 'cancelled'`),
  debit: db.prepare(`UPDATE subscriptions SET balance_sats = ?, updated_at = ? WHERE id = ?`),
  exhaust: db.prepare(`UPDATE subscriptions SET status='exhausted', updated_at=? WHERE id=?`),
  insertAlert: db.prepare(`INSERT INTO subscription_alerts (subscription_id, kind, payload_json, signature, sats_charged, created_at) VALUES (?, ?, ?, ?, ?, ?)`),
  lastAlertKind: db.prepare(`SELECT kind FROM subscription_alerts WHERE subscription_id = ? ORDER BY created_at DESC LIMIT 1`),
  listAlerts: db.prepare(`SELECT id, kind, payload_json, signature, sats_charged, created_at FROM subscription_alerts WHERE subscription_id = ? AND created_at > ? ORDER BY created_at ASC`),
  seen: db.prepare(`INSERT OR IGNORE INTO seen_advisories(ghsa_id, seen_at) VALUES(?, ?)`),
  isSeen: db.prepare(`SELECT 1 FROM seen_advisories WHERE ghsa_id = ?`),
};

function debitAndAlert(subscription_id, kind, payload, signature) {
  const tx = db.transaction(() => {
    const sub = sql.get.get(subscription_id);
    if (!sub) return { ok: false, reason: "not_active" };
    if (sub.status !== "active") return { ok: false, reason: "not_active" };
    if (sub.balance_sats < sub.per_event_sats) {
      sql.exhaust.run(Date.now(), subscription_id);
      const last = sql.lastAlertKind.get(subscription_id);
      if (last?.kind !== "balance_exhausted") {
        sql.insertAlert.run(subscription_id, "balance_exhausted",
          JSON.stringify({ balance_sats: sub.balance_sats, per_event_sats: sub.per_event_sats }),
          signature, 0, Date.now());
      }
      return { ok: false, reason: "exhausted", balance_after: sub.balance_sats };
    }
    const newBal = sub.balance_sats - sub.per_event_sats;
    sql.debit.run(newBal, Date.now(), subscription_id);
    const r = sql.insertAlert.run(subscription_id, kind, JSON.stringify(payload), signature, sub.per_event_sats, Date.now());
    return { ok: true, alert_id: Number(r.lastInsertRowid), balance_after: newBal, sats_charged: sub.per_event_sats };
  });
  return tx();
}

function signAlert(kind, payload) {
  return createHmac("sha256", L402_SECRET || "fallback").update(JSON.stringify({ kind, payload })).digest("base64url");
}

function severityRank(s) {
  return { low: 1, medium: 2, high: 3, critical: 4 }[String(s).toLowerCase()] ?? 0;
}

// ─── advisory source ─────────────────────────────────────────────────
function loadFixture() {
  const fp = path.resolve(HERE, "fixtures", "advisories.json");
  return JSON.parse(fs.readFileSync(fp, "utf8"));
}

async function fetchRealAdvisories() {
  try {
    const r = await fetch("https://api.github.com/advisories?per_page=30", {
      headers: { "user-agent": "andromeda-market-monitor/0.1", "accept": "application/vnd.github+json" },
    });
    if (!r.ok) return [];
    return await r.json();
  } catch (e) {
    console.error(`[market-monitor] fetch advisories failed: ${e.message}`);
    return [];
  }
}

let mockAdvisoriesQueue = null;
async function nextAdvisories() {
  if (MOCK_MODE) {
    if (!mockAdvisoriesQueue) mockAdvisoriesQueue = loadFixture();
    return mockAdvisoriesQueue;
  }
  return fetchRealAdvisories();
}

function matches(advisory, config) {
  // Severity gate
  const minRank = severityRank(config.severity_min ?? "low");
  if (severityRank(advisory.severity) < minRank) return false;
  // Repo gate (mock fixture has affects_repos; real GitHub doesn't, so accept all)
  const repos = config.watched_repos;
  if (Array.isArray(repos) && repos.length > 0) {
    if (!Array.isArray(advisory.affects_repos)) {
      // real-mode advisories — match by package ecosystem name (best-effort)
      const pkgs = (advisory.vulnerabilities ?? []).map(v => v.package?.name).filter(Boolean);
      return repos.some(r => pkgs.some(p => r.toLowerCase().includes(p.toLowerCase()) || p.toLowerCase().includes(r.toLowerCase())));
    }
    return advisory.affects_repos.some(r => repos.includes(r));
  }
  return true;
}

async function watcherTick() {
  const advisories = await nextAdvisories();
  if (!Array.isArray(advisories)) return;
  for (const adv of advisories) {
    if (!adv.ghsa_id) continue;
    if (sql.isSeen.get(adv.ghsa_id)) continue;
    sql.seen.run(adv.ghsa_id, Date.now());

    const subs = sql.listActive.all("github-advisory-monitor");
    for (const sub of subs) {
      const cfg = JSON.parse(sub.config_json);
      if (!matches(adv, cfg)) continue;
      const payload = {
        ghsa_id: adv.ghsa_id,
        summary: adv.summary,
        severity: adv.severity,
        cve_id: adv.cve_id ?? null,
        published_at: adv.published_at,
        url: adv.repository_advisory_url ?? adv.html_url ?? null,
        affects: adv.affects_repos ?? null,
      };
      const sig = signAlert("advisory", payload);
      debitAndAlert(sub.id, "advisory", payload, sig);
    }
  }
}

// ─── http server ─────────────────────────────────────────────────────
function send(res, status, body, extraHeaders = {}) {
  const text = JSON.stringify(body);
  res.writeHead(status, { "content-type": "application/json", "content-length": Buffer.byteLength(text), ...extraHeaders });
  res.end(text);
}

async function readJson(req) {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", chunk => { data += chunk; });
    req.on("end", () => {
      if (!data) return resolve({ raw: "", json: null });
      try { resolve({ raw: data, json: JSON.parse(data) }); }
      catch { resolve({ raw: data, json: null }); }
    });
    req.on("error", reject);
  });
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    const p = url.pathname;
    const m = req.method;

    if (m === "GET" && p === "/api/health") {
      const id = identity;
      return send(res, 200, {
        ok: true, service: "andromeda-market-monitor", rev: "v0.1.0",
        andromeda_pubkey: id?.pubkey ?? null,
        wallet_mode: MOCK_MODE ? "mock" : "real",
        registry_url: REGISTRY_URL,
      });
    }

    if (m === "GET" && p === "/api/v1/discovery") {
      const id = identity;
      return send(res, 200, {
        schema: "andromeda.directory.v1",
        provider: { id: "market-monitor", pubkey: id?.pubkey, url: PUBLIC_URL },
        services: [{
          id: "github-advisory-monitor",
          endpoint: `${PUBLIC_URL}/api/v1/subscribe`,
          method: "POST",
          category: "monitoring.security",
          description: "Subscribe to GitHub Security Advisory feed; pay 50 sat per delivered alert that matches your watched_repos + severity_min config.",
          price_sats_per_event: 50,
          default_deposit_sats: 1000,
          subscription_only: true,
        }],
      });
    }

    if (m === "POST" && p === "/api/v1/subscribe") {
      const { json } = await readJson(req);
      if (!json || !json.subscriber_pubkey || !json.deposit_sats) {
        return send(res, 400, { error: "subscriber_pubkey + deposit_sats required" });
      }
      const id = `sub_${randomUUID().replace(/-/g, "").slice(0, 24)}`;
      const per_event = json.per_event_sats ?? 50;
      const now = Date.now();
      sql.create.run(id, json.subscriber_pubkey, "github-advisory-monitor",
        per_event, json.deposit_sats, JSON.stringify(json.config ?? {}), now, now);
      return send(res, 200, {
        ok: true, subscription_id: id, service_local_id: "github-advisory-monitor",
        per_event_sats: per_event, balance_sats: json.deposit_sats, status: "active",
        created_at: new Date(now).toISOString(),
      });
    }

    let m2 = p.match(/^\/api\/v1\/subscriptions\/([^\/]+)$/);
    if (m === "GET" && m2) {
      const sub = sql.get.get(m2[1]);
      if (!sub) return send(res, 404, { error: "no such subscription" });
      return send(res, 200, {
        id: sub.id, subscriber_pubkey: sub.subscriber_pubkey,
        service_local_id: sub.service_local_id, per_event_sats: sub.per_event_sats,
        balance_sats: sub.balance_sats, status: sub.status,
        config: JSON.parse(sub.config_json),
        created_at: new Date(sub.created_at).toISOString(),
        updated_at: new Date(sub.updated_at).toISOString(),
      });
    }

    m2 = p.match(/^\/api\/v1\/subscriptions\/([^\/]+)\/topup$/);
    if (m === "POST" && m2) {
      const { json } = await readJson(req);
      if (!json?.sats || !Number.isInteger(json.sats) || json.sats < 1) return send(res, 400, { error: "sats must be positive int" });
      if (!sql.get.get(m2[1])) return send(res, 404, { error: "no such subscription" });
      const r = sql.topup.run(json.sats, Date.now(), m2[1]);
      if (r.changes === 0) return send(res, 409, { error: "subscription cancelled" });
      const sub = sql.get.get(m2[1]);
      return send(res, 200, { ok: true, subscription_id: m2[1], balance_sats: sub.balance_sats, status: sub.status });
    }

    m2 = p.match(/^\/api\/v1\/subscriptions\/([^\/]+)\/cancel$/);
    if (m === "POST" && m2) {
      const sub = sql.get.get(m2[1]);
      if (!sub) return send(res, 404, { error: "no such subscription" });
      if (sub.status !== "active") return send(res, 409, { error: "already cancelled or exhausted" });
      const refunded = sub.balance_sats;
      sql.cancel.run(Date.now(), m2[1]);
      return send(res, 200, { ok: true, subscription_id: m2[1], refunded_sats: refunded, status: "cancelled" });
    }

    m2 = p.match(/^\/api\/v1\/subscriptions\/([^\/]+)\/alerts$/);
    if (m === "GET" && m2) {
      if (!sql.get.get(m2[1])) return send(res, 404, { error: "no such subscription" });
      const since = parseInt(url.searchParams.get("since") ?? "0", 10);
      const rows = sql.listAlerts.all(m2[1], since);
      return send(res, 200, {
        subscription_id: m2[1], since, count: rows.length,
        alerts: rows.map(r => ({
          id: r.id, kind: r.kind, payload: JSON.parse(r.payload_json),
          signature: r.signature, sats_charged: r.sats_charged,
          created_at: new Date(r.created_at).toISOString(),
          created_at_ms: r.created_at,
        })),
      });
    }

    if (m === "POST" && p === "/api/dev/fire-alert") {
      if (!MOCK_MODE) return send(res, 404, { error: "dev endpoint disabled" });
      const { json } = await readJson(req);
      if (!json?.subscription_id || !json?.kind) return send(res, 400, { error: "subscription_id + kind required" });
      const sig = signAlert(json.kind, json.payload ?? {});
      const r = debitAndAlert(json.subscription_id, json.kind, json.payload ?? {}, sig);
      return send(res, 200, r);
    }

    if (m === "POST" && p === "/api/dev/tick") {
      if (!MOCK_MODE) return send(res, 404, { error: "dev endpoint disabled" });
      await watcherTick();
      return send(res, 200, { ok: true, ticked: true });
    }

    send(res, 404, { error: "not found", path: p, method: m });
  } catch (e) {
    console.error("[market-monitor] handler error:", e.stack || e.message);
    send(res, 500, { error: "internal", message: e.message });
  }
});

// ─── registry self-registration ──────────────────────────────────────
async function registerWithRegistry() {
  const id = await ensureIdentity();
  const path = "/api/v1/sellers/register";
  const body = JSON.stringify({
    pubkey: id.pubkey,
    name: "market-monitor",
    url: PUBLIC_URL,
    description: "Sells GitHub Security Advisory subscriptions: 50 sat per delivered alert, default 1000 sat deposit. Filter by repo + severity.",
    services: [{
      local_id: "github-advisory-monitor",
      name: "GitHub advisory monitor",
      description: "Subscribe to GitHub security advisories; pay per delivered alert that matches your watched_repos + severity_min config. Polling delivery.",
      type: "monitoring",
      tags: ["security", "github", "monitoring", "advisories", "subscription"],
      price_sats: 50, // per-event
      p50_ms: 200,
      endpoint: `${PUBLIC_URL}/api/v1/subscribe`,
    }],
  });
  try {
    const headers = await signRequest({ method: "POST", path, body, privkeyHex: id.privkey, pubkeyHex: id.pubkey });
    const r = await fetch(`${REGISTRY_URL}${path}`, {
      method: "POST",
      headers: { "content-type": "application/json", ...headers },
      body,
    });
    if (!r.ok) console.error(`[market-monitor] register failed: ${r.status} ${(await r.text()).slice(0, 200)}`);
    else console.error(`[market-monitor] registered with ${REGISTRY_URL}; pubkey=${id.pubkey}`);
  } catch (e) {
    console.error(`[market-monitor] register error: ${e.message}`);
  }
}

// ─── boot ────────────────────────────────────────────────────────────
async function boot() {
  await ensureIdentity();
  server.listen(PORT, () => {
    console.error(`[market-monitor] listening on :${PORT} (${MOCK_MODE ? "mock" : "real"} mode)`);
  });
  // Register & start heartbeat.
  await registerWithRegistry();
  setInterval(() => { void registerWithRegistry().catch(() => {}); }, 60_000);
  // Watcher loop.
  setInterval(() => { void watcherTick().catch(e => console.error("[market-monitor] tick error:", e.message)); }, WATCHER_INTERVAL);
}

process.on("SIGINT", () => { server.close(); db.close(); process.exit(0); });
process.on("SIGTERM", () => { server.close(); db.close(); process.exit(0); });

boot().catch(e => {
  console.error("[market-monitor] fatal:", e.stack || e.message);
  process.exit(1);
});
