// Provider identity: Ed25519 keypair persisted in .env.local.
//
// On first boot, if ANDROMEDA_PROVIDER_PRIVKEY is unset, we generate
// one and append it to .env.local. The pubkey is the provider's id.

import { readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import path from "node:path";
import { generateKeypair, pubkeyFor } from "@andromeda/core";

let cached: { privkey: string; pubkey: string } | null = null;

function envFilePath(): string {
  // provider runs with cwd = provider/, so .env.local is here.
  return path.resolve(process.cwd(), ".env.local");
}

export async function ensureIdentity(): Promise<{ privkey: string; pubkey: string }> {
  if (cached) return cached;
  let privkey = process.env.ANDROMEDA_PROVIDER_PRIVKEY;
  if (!privkey) {
    const kp = await generateKeypair();
    privkey = kp.privkey_hex;
    const fp = envFilePath();
    const line = `\n# auto-generated by Andromeda provider on first boot\nANDROMEDA_PROVIDER_PRIVKEY=${privkey}\n`;
    try {
      if (existsSync(fp)) appendFileSync(fp, line, "utf8");
      else writeFileSync(fp, line, "utf8");
      process.stderr.write(`[andromeda] generated provider keypair; pubkey=${kp.pubkey_hex}\n`);
    } catch (e) {
      process.stderr.write(`[andromeda] WARNING: could not persist generated key to ${fp}: ${(e as Error).message}\n`);
    }
    process.env.ANDROMEDA_PROVIDER_PRIVKEY = privkey;
    cached = { privkey, pubkey: kp.pubkey_hex };
    return cached;
  }
  const pubkey = await pubkeyFor(privkey);
  cached = { privkey, pubkey };
  return cached;
}

/** Synchronous accessor; throws if ensureIdentity hasn't been awaited yet. */
export function identityOrThrow(): { privkey: string; pubkey: string } {
  if (!cached) throw new Error("identity not initialized; await ensureIdentity() first");
  return cached;
}

export function tryIdentity(): { privkey: string; pubkey: string } | null {
  return cached;
}
